### ISSUE TITLE
无法查看server 崩溃的log信息

### ISSUE THREAD

**Issue by HelloCui** [Ysheep666/express-template#1]
我们用 grunt server 启动服务，当服务器出错崩溃的时候，我们能够得到的信息只是“application exited with code 8”。我们希望能够得到完整的错误信息，请问该怎样配置Gruntfile改怎么配置？

**Comment by Ysheep666** [comment]
使用 grunt-nodemon 吧

**Comment by HelloCui** [comment]
换成grunt-nodemon就可以了，谢谢！
